/* Shared seed data for the Yekoraa demo. In-memory only — resets on reload. */

const YEKORAA_AUCTIONS = [
  {
    id: 1,
    title: "Vintage Bronze Benin Mask",
    seller: "AdunniArts",
    category: "Art & Antiques",
    location: "Lagos",
    condition: "Used — Excellent",
    img: "https://images.unsplash.com/photo-1618172193622-ae2d025f4032?q=80&w=900&auto=format&fit=crop",
    desc: "Hand-cast bronze mask, private collection provenance. Minor age patina consistent with authenticity.",
    startBid: 45000,
    bid: 62000,
    bids: 14,
    seconds: 42,
  },
  {
    id: 2,
    title: "iPhone 14 Pro — Mint, Boxed",
    seller: "TechDepotNG",
    category: "Electronics",
    location: "Abuja",
    condition: "New — Sealed",
    img: "https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?q=80&w=900&auto=format&fit=crop",
    desc: "Factory unlocked, 256GB, Deep Purple. Full original packaging and accessories included.",
    startBid: 280000,
    bid: 402500,
    bids: 27,
    seconds: 18,
  },
  {
    id: 3,
    title: "Ankara Set — Custom Tailored",
    seller: "Zainab Couture",
    category: "Fashion",
    location: "Ibadan",
    condition: "New — Made to order",
    img: "https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?q=80&w=900&auto=format&fit=crop",
    desc: "Two-piece Ankara set, adjustable sizing on request. Fabric sourced from Balogun Market.",
    startBid: 15000,
    bid: 21000,
    bids: 6,
    seconds: 240,
  },
  {
    id: 4,
    title: "Generator — Fuel-less 3.5kVA",
    seller: "PowerHubLagos",
    category: "Home & Appliances",
    location: "Lagos",
    condition: "New",
    img: "https://images.unsplash.com/photo-1610901157620-340856d0a50f?q=80&w=900&auto=format&fit=crop",
    desc: "Silent-running inverter generator. 1-year warranty, delivery available within Lagos.",
    startBid: 120000,
    bid: 168000,
    bids: 19,
    seconds: 95,
  },
  {
    id: 5,
    title: "Hand-Woven Aso-Oke Fabric (5 yards)",
    seller: "Ilé Textiles",
    category: "Fashion",
    location: "Oyo",
    condition: "New",
    img: "https://images.unsplash.com/photo-1590736969955-71cc94901144?q=80&w=900&auto=format&fit=crop",
    desc: "Traditional loom-woven Aso-Oke, gold and wine colourway. Ideal for aso-ebi or ceremonial wear.",
    startBid: 30000,
    bid: 41000,
    bids: 9,
    seconds: 320,
  },
  {
    id: 6,
    title: "PlayStation 5 Slim — 1TB",
    seller: "GameVaultNG",
    category: "Electronics",
    location: "Port Harcourt",
    condition: "Used — Like new",
    img: "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?q=80&w=900&auto=format&fit=crop",
    desc: "Comes with 2 controllers and 3 titles. Purchased 4 months ago, receipt available.",
    startBid: 520000,
    bid: 587000,
    bids: 22,
    seconds: 61,
  },
  {
    id: 7,
    title: "Leather Executive Office Chair",
    seller: "OfficeEdge",
    category: "Home & Appliances",
    location: "Lagos",
    condition: "New",
    img: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?q=80&w=900&auto=format&fit=crop",
    desc: "Ergonomic high-back chair, adjustable lumbar support. Bulk lots available for offices.",
    startBid: 60000,
    bid: 74000,
    bids: 5,
    seconds: 500,
  },
  {
    id: 8,
    title: "Gold-Plated Coral Bead Set",
    seller: "Heritage Beads Co.",
    category: "Art & Antiques",
    location: "Benin City",
    condition: "New",
    img: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?q=80&w=900&auto=format&fit=crop",
    desc: "Traditional coral bead set for ceremonial wear — necklace, bracelet, and crown piece.",
    startBid: 85000,
    bid: 103000,
    bids: 11,
    seconds: 150,
  },
];

function yekFmtNaira(n) {
  return "₦" + Math.round(n).toLocaleString("en-NG");
}

function yekGetAuction(id) {
  return YEKORAA_AUCTIONS.find((a) => a.id === Number(id));
}
